apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ks-image-
spec:
  podGC:
    strategy: OnPodSuccess # delete pods when workflow is successful
  entrypoint: main
  arguments:
    parameters:
    - name: git_ref_type
      value: branches
    - name: git_version
  templates:
  - name: main
    inputs:
      parameters:
      - name: git_ref_type
      - name: git_version
      - name: repo_name
        value: quay.io/bradfordwagner/ks
      - name: upstream_repo
        value: quay.io/bradfordwagner/go-builder
      - name: upstream_tag
        value: 2.5.0
    dag:
      tasks:
      - name: go-builder
        arguments:
          parameters:
          - name: git_repo
            value: https://github.com/bradfordwagner/ks.git
          - name: git_version
            value: "{{ inputs.parameters.git_version }}"
          - name: upstream_repo
            value: "{{ inputs.parameters.upstream_repo }}"
          - name: upstream_tag
            value: "{{ inputs.parameters.upstream_tag }}"
          - name: repo_name
            value: "{{ inputs.parameters.repo_name }}"
          - name: platform
            value: "{{ item.platform }}"
          - name: go_main_path
            value: ./cmd/ks
          - name: runtime_platforms
            value: "{{ item.runtime_platforms }}"
          - name: tag_suffix
            value: "-{{ item.platform }}"
        templateRef:
          name: flavor-go-template
          template: "{{inputs.parameters.git_ref_type}}"
        withItems:
        - { platform: alpine_3.16, runtime_platforms: [linux/arm64] }

